### ISSUE TITLE
References to atto have got into the readme

### ISSUE THREAD

**Issue by marcusgreen** [srobotta/moodle-tiny_cloze#10]
The readme has the following text

"To install add to the Atto editor plugins directory and visit notifications to update database. This directory must be named 'cloze' in lib/editor/atto/plugins. Then add 'cloze' to the list of buttons in Atto toolbar settings at Site administration -> Plugins -> Text editors -> Atto HTML editor -> Atto toolbar settings."

Where it should say tiny. I will create a pull myself when I get the chance

**Comment by lucaboesch** [comment]
Oh, sorry, @marcusgreen ! I was in a hurry…

**Comment by srobotta** [comment]
Thank you @marcusgreen, I noticed it but was busy with other things.
Also: you can change it directly as you have the permission and are part of the maintainer/developer. There's no need for a pull request.

**Comment by marcusgreen** [comment]
I will change it

**Comment by marcusgreen** [comment]
I have updated it. Thank you srobotta and lucaboesch, I am finding this project very inspiring, and excellent for learning.

**Comment by srobotta** [comment]
Thank you @marcusgreen for updating the README.
