### ISSUE TITLE
Error when an answer is left blank

### ISSUE THREAD

**Issue by Kemmotar83** [srobotta/moodle-tiny_cloze#18]
Hi,

when creating a MULTICHOICE or a MULTIRESPONSE question (with all variants) and an answer is left blank, the editor creates a malformed cloze string in the question text, adding an unwanted ~ char also for the blank answer.

Steps to reproduce the error:
- Create a new _Cloze_ question
- In _Question text_ field, click on the _Cloze question editor_ button
- Select MULTICHOICE question type
- Fill _1. Answer_ and _2. Answer_ with text (i.e. _first option_ and _second option_)
- Select the _Correct_ grade for the first answer
- Leave the third answer blank
- Click on the _Insert question_ button
- Verify that the cloze text is `{1:MULTICHOICE:=first option~second option~}` with a ~ also for the blank answer

Suggestion: the blank answer should be ignored when processing the answers, since that last ~ cause an error in the question.

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/3964915/822f6b99-f456-45f3-99d6-c3fb8f79676d)

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/3964915/bd9a7cf2-db26-4234-bec2-e13d01832514)

Thanks,
Giorgio

**Comment by srobotta** [comment]
Hi Giorgio,

Thank you for your bug report. I have addressed the issue and fixed it in the way to validate the input fields and show an error message in the dialogue without closing it and saving the question string.
The changes are in the main branch, I have not yet created a new release.

Best regards, Stephan

**Comment by srobotta** [comment]
Hi Giorgio,

I drafted a new release v1.5.

Best regards, Stephan
