### ISSUE TITLE
Cloze button missing

### ISSUE THREAD

**Issue by AlI555aa** [srobotta/moodle-tiny_cloze#19]
Hello

Moodle 4.3.3 (fresh installation) updated to 4.3.3+ (Boost theme). My issue is the absence of the Cloze button. Could you please help?"
![Screenshot 2024-03-13 173926](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/93557487-b282-4102-983b-c29ad7c968f0)
![Screenshot 2024-03-13 173956](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/d0b5f8cd-8d47-400a-ad3d-74558958c6ed)
![Screenshot 2024-03-13 174032](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/15768345-b3b4-4b59-ab7d-56750a5f4a4c)
![Screenshot 2024-03-13 180259](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/cefa3d95-1ea7-4449-b3e4-5cdedde30931)

**Comment by srobotta** [comment]
Hi,

the cloze button appears on the question text editor only for the moment. It does not yet check for the existense of the embedded question plugin.

Best regards, Stephan

**Comment by AlI555aa** [comment]
Hello

Thank you for the response. The plugin exists. Could you please tell me if there are any other settings somewhere else that need to be changed?

![Screenshot 2024-03-13 213259](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/28f7a742-06b3-4782-94f9-aa8533ac6c64)

**Comment by AlI555aa** [comment]
Hello

Thank you for the response. The plugin exists. Could you please tell me if there are any other settings somewhere else that need to be changed?
![Screenshot 2024-03-13 213259](https://github.com/srobotta/moodle-tiny_cloze/assets/163328582/b7465abf-fbb1-420e-afd7-3721b2249c0a)

**Comment by srobotta** [comment]
Hi again,

what I am saying is that you will see the cloze button in the editor only when editing a question in the question text field. For other fields the cloze question syntax does not make sense.
Now: when you have the plugin embedded question installed, you may edit questions in other places as well, not only in the question (text) itself. However, the cloze question tiny plugin currently does not check for the existence of the embedded question plugin, so the button is missing except for the question text editor.
I would have to have a look on how to combine the cloze question tiny plugin when the ebedded question plugin is installed.
On the other hand, there will be a button for the tinyMCE to embedd questions very soon. Let's see how this will go together.

**Comment by AlI555aa** [comment]
Hello,

Thank you once again for the response. Unfortunately, I couldn't find the button, so I found a solution through the Atto editor for now. Please close the topic (but before that, may I ask: when will the change you mentioned be implemented?).

Best regards,

**Comment by srobotta** [comment]
I was checking that again. An embeded question is selected from the list of categories and there from the question inside the categories. The question cannot be edited where it is embedded (at least that I know of). Therefore I guess, it doesn't make sense to have the cloze question button in the TinyMCE only when editing the question text itself. Please let me know if I am wrong and missed a use case.
I am closing this. Please open a new issue and describe the desired behaviour.
